name: CI/CD
on: [push,pull_request]
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install dependences
        run: npm install --legacy-peer-deps
      - name: Build front 
        run: npm run build --legacy-peer-deps
      - name: Run tests
        run: npm test
      - name: Run server for e2e tests
        run: npm start &
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      

